services:
  postgres:
    image: 'postgres:17.2-alpine3.21'
    environment:
      - 'POSTGRES_DB=domain_event_db'
      - 'POSTGRES_USER=user'
      - 'POSTGRES_PASSWORD=password'
    ports:
      - '5432:5432'
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
